name: On push

on: push

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '4.0'
      - run: BUNDLE_FROZEN=true bundle install
      - run: rake test

  docker:
    name: 'Test Docker image'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: docker compose -f docker-compose.test.yml up -d --build --wait
      - run: curl -Is http://localhost:3000/healthcheck
      - run: curl -Is http://localhost:3000/test-token/sample

  deploy:
    name: 'Deploy'
    needs: [docker]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
      - uses: 12joan/build-and-push-image@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

